services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: boilerplate
      POSTGRES_DB: boilerplate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "boilerplate", "-d", "boilerplate_db" ]
      interval: 5s
      retries: 5
    networks:
      shared_proxy_net:
        aliases:
          - project1_db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/code
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://boilerplate:boilerplate@postgres:5432/boilerplate_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      shared_proxy_net:
        aliases:
          - project1_backend

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
      - "24678:24678"

    command: sh -c "npm install && npm run dev -- --host"

    networks:
      shared_proxy_net:
        aliases:
          - project1_frontend

volumes:
  postgres_data:

networks:
  shared_proxy_net:
    external: true